baseurl = "https://hhcheng.netlify.app/"
languageCode = "zh-cn"
title = "Rblog|Huang's personal blog"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
enableGitInfo = "true"

# new setting
draft = false # if set to true, changes will not be published
enableEmoji = true

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = "2"
[[menu.main]]
    name = "Categories"
    url = "/Categories/"
    weight = "3"
[[menu.main]]
    name = "Tags"
    url = "/Tags/"
    weight = "4"
    
[[menu.main]]
    name = "Notebooks"
    url = "/notebooks/"
    weight = "5"

[[menu.footer]]
    name = "GitHub"
    url = "https://github.com/huanghaicheng1024"
    weight = "1"

[params]
    description = "A website built through Hugo and blogdown.A blog website of Huang"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "10.0.3"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml" ,"css"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "myfavicon.ico"


    [params.logo]
    url = "mylogo.png"
    width = 50
    height = 50
    alt = "Logo"
    
  # Custom CSS. Put here your custom CSS files. They are loaded after the theme CSS;
  # they have to be referred from static root. Example
    [params.customCSS]
     href = "css/my-style.css"

  # Custom JS. Put here your custom JS files. They are loaded after the theme JS;
  # they have to be referred from static root. Example
    [params.customJS]
     src = "js/myjs.js"

  [params.utteranc]
  enable = true
  repo = "huanghaicheng1024/Blog-comments"    # 存储评论的Repo，格式为 owner/repo
  issueTerm = "title"           # 表示你选择以那种方式让github issue的评论和你的文章关联可以选择默认的pathname。
  theme = "github-light"        # 样式主题
