baseurl = "https://huanghaicheng1024.github.io/Rblog/"
publishDir = "docs"
languageCode = "en-us"
title = "Rblog"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# new setting
draft = false # if set to true, changes will not be published
enableEmoji = true

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = "2"
[[menu.main]]
    name = "Categories"
    url = "/Categories/"
    weight = "3"
[[menu.main]]
    name = "Tags"
    url = "/Tags/"
    weight = "4"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/huanghaicheng1024"
    weight = "5"

[params]
    description = "A website built through Hugo and blogdown.A blog website of Huang"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "myfavicon.ico"


    [params.logo]
    url = "mylogo.png"
    width = 50
    height = 50
    alt = "Logo"
    
  # Custom CSS. Put here your custom CSS files. They are loaded after the theme CSS;
  # they have to be referred from static root. Example
    [params.customCSS]
     href = "css/my-style.css"

  # Custom JS. Put here your custom JS files. They are loaded after the theme JS;
  # they have to be referred from static root. Example
    [params.customJS]
     src = "js/myjs.js"

